openapi: 3.0.0
info:
  version: 1.0.0
  title: "Trentino Find OpenAPI"
  description: API per Trentino find.
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LUCACACCAVALE/TrentinoFind/1.0.0
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /giocatori:
    post:
      tags:
        - giocatore
      description: >-
        Crea un nuovo giocatore all'interno del sistema.
      summary: Crea un nuovo giocatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Giocatore'
        required: true
      responses:
        '201':
          description: 'Giocatore creato. Link nel Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link al nuovo giocatore creato
        '405':
          description: Invalid input
  
  /giocatori/{ID}:
    put:
      tags:
        - giocatore
      parameters:
        - name: ID
          in: path
          description: ID del giocatore da modificare
          required: true
          schema:
            type: integer
            format: int64
      description: >-
        Aggiorna un giocatore all'interno del sistema.
      summary: Aggiorna un giocatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Giocatore'
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
    get:
      tags:
        - giocatore
      parameters:
        - name: ID
          in: path
          description: ID del giocatore da visualizzare
          required: true
          schema:
            type: integer
            format: int64
      description: >-
        Ottiene le informazioni personali di un giocatore all'interno del sistema.
      summary: Visualizza informazioni personali di un giocatore.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Giocatore'
        '405':
          description: Invalid input

components:
  schemas:
    Giocatore:
      type: object
      required:
        - email
        - firstname
        - lastname
        - age
        - phone
      properties:
       email:
          type: string
          description: 'Indirizzo email del giocatore'
       firstname: 
          type: string
          description: 'Nome del giocatore'
       lastname: 
          type: string
          description: 'Cognome del giocatore'
       age: 
          type: string
          description: 'Età del giocatore'
       phone: 
          type: string
          description: 'Numero di telefono del giocatore'