openapi: 3.0.0
info:
  version: '1.0'
  title: "Trentino Find OpenAPI"
  description: API for managing book lendings.
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /giocatori:
    post:
      tags:
        - giocatore
      description: >-
        Crea un nuovo giocatore all'interno del sistema.
      summary: Crea un nuovo giocatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Giocatore'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Giocatore'
        '405':
          description: Invalid input
          
  /giocatori/{ID}:
    put:
      tags:
        - giocatore
      description: >-
        Aggiorna i dati forniti in fase di un giocatore all'interno del sistema.
      summary: Crea un nuovo giocatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Giocatore'
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input

  /books:
    get:
      description: >-
        Gets the list of books.
      summary: View all books
      responses:
        '200':
          description: 'Collection of books'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /booklendings:
    post:
      description: >-
        Creates a new booklending.
      summary: Borrow a book
      responses:
        '201':
          description: 'Booklending created. Link in the Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link to the newly created booklending.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booklending'
          
components:
  schemas:
    Giocatore:
      type: object
      required:
        - email
        - firstname
        - lastname
        - age
        - phone
      properties:
       email:
          type: string
          description: 'Indirizzo email del giocatore'
       firstname: 
          type: string
          description: 'Nome del giocatore'
       lastname: 
          type: string
          description: 'Cognome del giocatore'
       age: 
          type: string
          description: 'Età del giocatore'
       phone: 
          type: string
          description: 'Numero di telefono del giocatore'

    Book:
      type: object
      required:
        - title
        - author
        - ISBN
        - status
      properties:
        title:
          type: string
          description: 'Title of the book'
        author:
          type: string
          description: 'Author of the book'
        ISBN:
          type: string
          description: 'ISBN of the book'
        status:
          type: string
          enum: [available, lended]
          description: 'Tells whether the book is currently available or not'
    Booklending:
      type: object
      required:
      - student
      - book
      properties:
        user:
          type: string
          description: 'Link to the user'
        book:
          type: integer
          description: 'Link to the book'