openapi: 3.0.0
info:
  version: 1.0.0
  title: "Trentino Find OpenAPI"
  description: API per Trentino find.
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LUCACACCAVALE/TrentinoFind/1.0.0
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /giocatori:
    post:
      tags:
        - giocatore
      description: >-
        Crea un nuovo giocatore all'interno del sistema.
      summary: Crea un nuovo giocatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Giocatore'
        required: true
      responses:
        '201':
          description: 'Registrazione avvenuta. Link nel Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link al nuovo giocatore creato
        '400':
          description: 'Non è possibile effetuare la registrazione'
          content:
            application/json:
              schema:
                type: string
                description: Descrizione dell'errore in fase di registrazione
                
  /giocatori/{ID}:
    put:
      tags:
        - giocatore
      parameters:
        - name: ID
          in: path
          description: ID del giocatore da modificare
          required: true
          schema:
            type: integer
            format: int64
      description: >-
        Aggiorna un giocatore all'interno del sistema.
      summary: Aggiorna un giocatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Giocatore'
      responses:
        '200':
          description: Modifica avvenuta con successo
        '400':
          description: Modifica non avvenuta
          content:
            application/json:
              schema:
                type: string
                description: Descrizione dell'errore che non ha permesso la modifica
        '401':
          description: Non autorizzato
    get:
      tags:
        - giocatore
      parameters:
        - name: ID
          in: path
          description: ID del giocatore da visualizzare
          required: true
          schema:
            type: integer
            format: int64
      description: >-
        Ottiene le informazioni personali di un giocatore all'interno del sistema.
      summary: Ottiene le informazioni personali di un giocatore.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Giocatore'
        '400':
          description: ID del giocatore non valido
        '401':
          description: Non autorizzato
          
  /oggetti/{ID}:      
     get:
      tags:
        - oggetto
      parameters:
        - name: ID
          in: path
          description: ID dell'oggetto da visualizzare
          required: true
          schema:
            type: integer
            format: int64
      description: >-
        Ottiene le informazioni di un oggetto all'interno del sistema.
      summary: Ottiene le informazioni di un oggetto.
      responses:
        '200':
          description: Operazione avvenuta con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oggetto'
        '400':
          description: ID dell'oggetto non valido
        '401':
          description: Non autorizzato
          
  /oggettiTrovati:
    post:
      description: >-
        Crea un nuovo ritrovamento di un oggetto da parte di un 
        giocatore all'interno del sistema.
      summary: Crea un nuovo ritrovamento di un oggetto da parte di un giocatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OggettoTrovato'
        required: true
      responses:
        '200':
          description: Il ritrovamento è stato inserito con successo
        '400':
          description: 'Non è stato possibile validare il ritrovamento'
          content:
            application/json:
              schema:
                type: string
                description: Descrizione dell'errore
        '401':
          description: Non autorizzato
    

          
  /authentication:
    post:
      tags:
        - login
      description: >-
          fa accere l'utente alla piattaforma
      summary: accesso alla piattaforma
      requestBody:
        content:
          application/json:
            schema:
              
        required: true
      responses:
        '201':
          description: 'Accesso avvenuto'
          headers:
            'Accesso':
              schema:
                type: string
              description: contiene il token creato
        '400':
          description: 'Accesso negato, credenziali non valide'
          content:
            application/json:
              schema:
                type: string
                description: Accesso negato
  
  
  /amministratori:
    post:
      tags:
        - amministratore
      description: >-
        Crea un nuovo amministratore all'interno del sistema.
      summary: Crea un nuovo amministratore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amministratore'
        required: true
      responses:
        '201':
          description: 'Registrazione avvenuta. Link nel Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link al nuovo amministratore creato
        '400':
          description: 'Non è possibile effetuare la registrazione'
          content:
            application/json:
              schema:
                type: string
                description: Descrizione dell'errore in fase di registrazione
                
  /amministratori/{ID}:
    put:
      tags:
        - amministratore
      parameters:
        - name: ID
          in: path
          description: ID del amministratore da modificare
          required: true
          schema:
            type: integer
            format: int64
      description: >-
        Aggiorna un amministratore all'interno del sistema.
      summary: Aggiorna un amministratore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amministratore'
      responses:
        '200':
          description: Modifica avvenuta con successo
        '400':
          description: Modifica non avvenuta
          content:
            application/json:
              schema:
                type: string
                description: Descrizione dell'errore che non ha permesso la modifica
        '401':
          description: Non autorizzato
    get:
      tags:
        - amministratore
      parameters:
        - name: ID
          in: path
          description: ID del amministratore da visualizzare
          required: true
          schema:
            type: integer
            format: int64
      description: >-
        Ottiene le informazioni personali di un amministratore all'interno del sistema.
      summary: Ottiene le informazioni personali di un amministratore.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Amministratore'
        '400':
          description: ID del amministratore non valido
        '401':
          description: Non autorizzato
          
  /moderatori:
    post:
      tags:
        - amministratore
      description: Aggiungi un nuovo moderatore alla piattaforma.
      summary: Aggiungi un nuovo moderatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Moderatore'
        required: true
      responses:
        '201':
          description: Aggiunta del moderatore avvenuta con successo
        '400':
          description: Errore nell'aggiunta del moderatore
          content:
            application/json:
              schema:
                type: string
              description: Descrizione dell'errore durante l'aggiunta del moderatore

  /moderatori/{ID}:
    put:
      tags:
        - amministratore
      parameters:
        - name: ID
          in: path
          description: ID del moderatore da modificare
          required: true
          schema:
            type: integer
            format: int64
      description: Aggiorna le informazioni di un moderatore.
      summary: Aggiorna un moderatore.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Moderatore'
        required: true
      responses:
        '200':
          description: Modifica del moderatore avvenuta con successo
        '400':
          description: Errore nella modifica del moderatore
          content:
            application/json:
              schema:
                type: string
              description: Descrizione dell'errore durante la modifica del moderatore
        '401':
          description: Non autorizzato
    get:
      tags:
        - amministratore
      parameters:
        - name: ID
          in: path
          description: ID del moderatore da visualizzare
          required: true
          schema:
            type: integer
            format: int64
      description: Ottiene le informazioni di un moderatore.
      summary: Ottiene le informazioni di un moderatore.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Moderatore'
        '400':
          description: ID del moderatore non valido
        '401':
          description: Non autorizzato
    delete:
      tags:
        - amministratore
      parameters:
        - name: ID
          in: path
          description: ID del moderatore da rimuovere
          required: true
          schema:
            type: integer
            format: int64
      description: Rimuove un moderatore dalla piattaforma.
      summary: Rimuove un moderatore.
      responses:
        '200':
          description: Rimozione del moderatore avvenuta con successo
        '400':
          description: Rimozione del moderatore non avvenuta
        '401':
          description: Non autorizzato


                
components:
  schemas:
    Giocatore:
      type: object
      required:
        - email
        - firstname
        - lastname
        - age
        - phone
      properties:
       email:
          type: string
          description: 'Indirizzo email del giocatore'
       firstname: 
          type: string
          description: 'Nome del giocatore'
       lastname: 
          type: string
          description: 'Cognome del giocatore'
       age: 
          type: string
          description: 'Età del giocatore'
       phone: 
          type: string
          description: 'Numero di telefono del giocatore'
    Oggetto:
      type: object
      required:
        - title
        - description
        - dimension
        - difficulty
      properties:
       title:
          type: string
          description: "Il titolo dell'oggetto"
       description: 
          type: string
          description: "La descrizione dell'oggetto"
       dimension: 
          type: string
          description: "La dimensione dell'oggetto"
       difficulty: 
          type: string
          description: "La difficoltà dell'oggetto"
    OggettoTrovato:
      type: object
      required:
      - giocatore
      - oggetto
      - codiceDiValidazione
      properties:
        giocatore:
          type: string
          description: 'ID giocatore'
        oggetto:
          type: string
          description: 'ID oggetto'
        codiceDiValidazione:
          type: string
          description: 'Codice di ritrovamento oggetto'
          
    Amministratore:
      type: object
      required:
        - email
        - firstname
        - lastname
        - age
        - phone
      properties:
       email:
          type: string
          description: 'Indirizzo email del amministratore'
       firstname: 
          type: string
          description: 'Nome del amministratore'
       lastname: 
          type: string
          description: 'Cognome del amministratore'
       age: 
          type: string
          description: 'Età del amministratore'
       phone: 
          type: string
          description: 'Numero di telefono del amministratore'
          
          
          
          
    Moderatore:
      type: object
      required:
        - email
        - firstname
        - lastname
        - age
        - phone
      properties:
       email:
          type: string
          description: 'Indirizzo email del moderatore'
       firstname: 
          type: string
          description: 'Nome del moderatore'
       lastname: 
          type: string
          description: 'Cognome del moderatore'
       age: 
          type: string
          description: 'Età del moderatore'
       phone: 
          type: string
          description: 'Numero di telefono del moderatoreggi'